stages:
  - test
  - build

test:
  stage: test
  image: golang:1.17
  script: 
   - go test .
  tags:
    - notag

build:
  stage: build
  image: docker:latest
  services:
  - "docker:dind"
  script:
   - docker build .
  tags:
    - notag