stages:
  - test
  - build

test:
  stage: test
  image: golang:1.17
  script: 
   - go test .
  tags:
    - notag

build:
  stage: build
  image: docker:28.1.1-dind
  script:
   - docker build .
  tags:
    - notag